# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.TextField()),
                ('request_method', models.CharField(max_length=16)),
                ('request_url', models.CharField(max_length=65536)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_status_code', models.IntegerField()),
                ('response_body', models.TextField()),
            ],
        ),
    ]
